[profile.default]
evm_version = "cancun"
src = "src"
out = "out"
libs = ["lib"]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/",
    "@uniswap-v2-core/=lib/v2-core/",
    "@uniswap-v2-periphery/=lib/v2-periphery/",
    "solady/=lib/solady/"
]

[rpc_endpoints]
mainnet = "https://rpc.mevblocker.io"
polygon = "${POLYGON_RPC_URL}"
polygon_amoy = "${POLYGON_AMOY_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
polygon = { key = "${POLYGONSCAN_API_KEY}" }
polygon_amoy = { key = "${POLYGONSCAN_API_KEY}" }